### ISSUE TITLE
make temperature plausibility check optional

### ISSUE THREAD

**Issue by rhabel** [rnuske/vegperiod#5]
Hello and thanks for your package!
I am running the LWF-Brook90 model through LWFBrook90R with data from climate scenarios, but the stop-condition in vegperiod::vegperiod, line 177-181 stops me from running RCP8.5 scenarios until 2100, which include days with daily mean temperatures above 40 °C. It would be nice to have these kind of logical checks as options, not mandatory.
Thanks and best regards
Raphael

**Comment by rnuske** [comment]
Hi Raphael,

thanks for the very detailed report. 

We introduced the plausibility check after a former colleague did all his modelling with climate values that had been multiplied by ten to store them as integer (x * 10^-1). Plausibility thresholds are, of course, always arbitrary. In this case, they were chosen so that they do not hinder the work with the climate scenarios available to us. So your RCP 8.5 scenarios seem to be more extreme than ours (and even more extreme than the current heat wave in India).

I'm wavering between a) setting the thresholds a bit more extreme (e.g. -40 and +50) and b) introducing an additional parameter to make the plausibility check optional. Do you have any compelling arguments for either option?

cheers
  robert

**Comment by rhabel** [comment]
Hello Robert, 

thanks for your detailed response. 
Yes indeed, the szenario that exceeded your threshold was our most extreme one. 
Nevertheless, I am in favour of your second option. I think it is extremely valuable to provide this plausibility check for the user, but I'd prefer it as an optional feature. 
You could set the plausibility check default to TRUE, and throw a message such as "Your input temperature data exceeds the plausible range of -X to +Y°C. You may want to double check your data. If you still want to use given data, set _check.data_ to FALSE". That way, the first instance is causing a stop and an incentive to double check, but the option to continue is still there. 

Best regards, 
Raphael

**Comment by rnuske** [comment]
Thanks for your feedback. I like your wording will probabaly use something along those lines.
